theme = "monokai_pro"

[editor]
bufferline = "always"
true-color = true
text-width = 120

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name", "diagnostics"]
right = ["version-control", "selections", "position", "total-line-numbers", "file-encoding", "file-line-ending", "file-type"]

[editor.cursor-shape]
insert = "block"
normal = "hidden"
select = "hidden"

[editor.file-picker]
hidden = false

[editor.whitespace.render]
tab = "all"

[keys.normal]
# buffer
C-b     = "buffer_picker"           # open buffer picker
C-p     = "file_picker"             # open file picker
A-p     = "workspace_symbol_picker" # lsp - workspace symbols
"C-A-p" = "symbol_picker"           # lsp - file symbols
C-s     = ":write"                  # save buffer 
C-w     = ":buffer-close"           # close buffer
C-left  = "goto_previous_buffer"    # buffer left
C-right = "goto_next_buffer"        # buffer right
# code
C-z     = "undo"                    # undo last code edit
A-f     = ":format"                 # format code
"C-/"   = "toggle_comments"         # comment selected line
"A-/"   = "toggle_comments"         # comment selected line

[keys.insert]
# buffer
C-b     = "buffer_picker"           # open buffer picker
C-p     = "file_picker"             # open file picker
A-p     = "workspace_symbol_picker" # lsp - workspace symbols
"C-A-p" = "symbol_picker"           # lsp - file symbols
C-s     = ":write"                  # save buffer 
C-w     = ":buffer-close"           # close buffer
C-left  = "goto_previous_buffer"    # buffer left
C-right = "goto_next_buffer"        # buffer right
# code
C-z     = "undo"                    # undo last code edit
A-f     = ":format"                 # format code
"C-/"   = "toggle_comments"         # comment selected line
"A-/"   = "toggle_comments"         # comment selected line

[keys.select]
# buffer
C-b     = "buffer_picker"           # open buffer picker
C-p     = "file_picker"             # open file picker
A-p     = "workspace_symbol_picker" # lsp - workspace symbols
"C-A-p" = "symbol_picker"           # lsp - file symbols
C-s     = ":write"                  # save buffer 
C-w     = ":buffer-close"           # close buffer
C-left  = "goto_previous_buffer"    # buffer left
C-right = "goto_next_buffer"        # buffer right
# code
C-z     = "undo"                    # undo last code edit
A-f     = ":format"                 # format code
"C-/"   = "toggle_comments"         # comment selected line
"A-/"   = "toggle_comments"         # comment selected line
